import Link from "next/link";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Terms of Service — Peregrio",
  description: "Terms and conditions for using Peregrio.",
};

export default function TermsPage() {
  return (
    <main className="min-h-screen bg-white text-slate-900">
      <nav className="fixed top-0 w-full z-50 px-6">
        <div className="max-w-6xl mx-auto mt-4 px-6 h-14 flex items-center justify-between rounded-2xl bg-white/80 backdrop-blur-2xl border border-slate-200 shadow-sm">
          <Link href="/" className="text-base font-bold tracking-tight">
            peregr<span className="text-cyan-700">io</span>
          </Link>
          <div className="flex items-center gap-6 text-sm">
            <a href="/#features" className="text-slate-500 hover:text-slate-900 transition-colors hidden sm:block">Features</a>
            <a href="/pricing" className="text-slate-500 hover:text-slate-900 transition-colors hidden sm:block">Pricing</a>
            <a href="/#faq" className="text-slate-500 hover:text-slate-900 transition-colors hidden sm:block">FAQ</a>
            <a href="/login" className="text-slate-500 hover:text-slate-900 transition-colors hidden sm:block">Login</a>
            <a href="/pricing" className="px-4 py-1.5 rounded-lg btn-gradient text-white text-sm font-medium transition-all shadow-sm">
              Try Free
            </a>
          </div>
        </div>
      </nav>

      <div className="max-w-3xl mx-auto px-6 pt-36 pb-24">
        <header className="mb-12">
          <h1 className="text-4xl font-display font-bold tracking-tight text-slate-900 mb-4">
            Terms of Service
          </h1>
          <p className="text-slate-500">Last updated: April 12, 2026</p>
        </header>

        <article className="prose prose-slate prose-lg max-w-none
          prose-headings:font-display prose-headings:font-bold prose-headings:tracking-tight
          prose-h2:text-2xl prose-h2:mt-12 prose-h2:mb-4
          prose-p:leading-relaxed prose-p:text-slate-600
          prose-a:text-cyan-700 prose-a:no-underline hover:prose-a:underline
          prose-strong:text-slate-900
          prose-li:text-slate-600">

          <h2>Acceptance of Terms</h2>
          <p>
            By accessing or using Peregrio (&quot;the Service&quot;), you agree to be bound by these Terms of Service.
            If you do not agree, do not use the Service. We may update these terms from time to time, and
            continued use after changes constitutes acceptance of the updated terms.
          </p>

          <h2>Description of Service</h2>
          <p>
            Peregrio is a listing analytics tool for tour operators on Viator. The Service analyzes publicly
            available listing data, compares it against competitors, and generates AI-powered recommendations
            to help operators improve their visibility and bookings. The Service does not guarantee any
            specific ranking improvement or booking increase.
          </p>

          <h2>Account Registration</h2>
          <p>
            To access certain features, you must create an account with a valid email address and password.
            You are responsible for maintaining the confidentiality of your account credentials and for all
            activity that occurs under your account. You must notify us immediately of any unauthorized use.
          </p>

          <h2>Subscription, Billing, and Cancellation</h2>
          <ul>
            <li>Paid plans are billed monthly or annually through Stripe, depending on the option you select.</li>
            <li>You may cancel your subscription at any time through your account settings or the Stripe Customer Portal. Cancellation takes effect at the end of the current billing period.</li>
            <li>We do not offer refunds for partial billing periods. If you cancel mid-cycle, you retain access until the end of that period.</li>
            <li>We reserve the right to change pricing with 30 days&apos; notice. Price changes do not apply to the current billing cycle.</li>
          </ul>

          <h2>Acceptable Use</h2>
          <p>You agree not to:</p>
          <ul>
            <li>Scrape, crawl, or programmatically access the Peregrio website or API beyond normal use of the Service.</li>
            <li>Resell, redistribute, or sublicense data, reports, or recommendations generated by the Service.</li>
            <li>Use the Service to harm, harass, or deceive other users or third parties.</li>
            <li>Attempt to circumvent plan limits, access controls, or security measures.</li>
            <li>Upload malicious content or attempt to compromise the Service&apos;s infrastructure.</li>
          </ul>

          <h2>Intellectual Property</h2>
          <p>
            The Peregrio name, logo, website design, and proprietary algorithms are our intellectual property.
            Analysis reports generated for your listings are yours to use, but the underlying scoring methodology
            and AI models remain our property. You may not reverse-engineer, copy, or replicate our scoring system.
          </p>

          <h2>Disclaimer of Warranties</h2>
          <p>
            The Service is provided &quot;as is&quot; and &quot;as available&quot; without warranties of any kind, express or implied.
            We do not warrant that the Service will be uninterrupted, error-free, or that the results will be
            accurate or complete. Viator listing data is fetched from public APIs and may not always reflect
            real-time changes.
          </p>

          <h2>Limitation of Liability</h2>
          <p>
            To the maximum extent permitted by applicable law, Peregrio shall not be liable for any indirect,
            incidental, special, consequential, or punitive damages, including loss of profits, data, or
            bookings, arising from your use of or inability to use the Service. Our total liability for any
            claim shall not exceed the amount you paid us in the 12 months preceding the claim.
          </p>

          <h2>Governing Law</h2>
          <p>
            These terms are governed by applicable law. Any disputes arising from these terms or the Service
            shall be resolved through good-faith negotiation first, and if necessary, through binding
            arbitration or the courts of competent jurisdiction.
          </p>

          <h2>Contact</h2>
          <p>
            For questions about these terms, contact us at <a href="mailto:hello@peregrio.com">hello@peregrio.com</a>.
          </p>
        </article>
      </div>

      <footer className="py-12 px-6 border-t border-slate-100">
        <div className="max-w-6xl mx-auto flex flex-col md:flex-row items-center justify-between gap-6">
          <div className="flex items-center gap-3">
            <Link href="/" className="text-base font-bold tracking-tight text-slate-900">
              peregr<span className="text-cyan-700">io</span>
            </Link>
            <span className="text-slate-400 text-sm">Listing intelligence for tour operators</span>
          </div>
          <div className="flex gap-8 text-sm text-slate-400">
            <Link href="/contact" className="hover:text-slate-900 transition-colors">Contact</Link>
            <Link href="/pricing" className="hover:text-slate-900 transition-colors">Pricing</Link>
            <Link href="/blog" className="hover:text-slate-900 transition-colors">Blog</Link>
            <Link href="/privacy" className="hover:text-slate-900 transition-colors">Privacy</Link>
            <Link href="/terms" className="hover:text-slate-900 transition-colors">Terms</Link>
          </div>
        </div>
      </footer>
    </main>
  );
}
